web_app/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views


urlpatterns = [
    path('register/', views.register, name="register"),
    path('login/', auth_views.LoginView.as_view(), name="login"),
    path('logout/', auth_views.LogoutView.as_view(), name="logout"),
]

web_app/api/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views as api_views

urlpatterns = [
    path('profile/delete/solution/<int:pk>/', api_views.delete_solution, name="delete_solution"),
    path('profile/delete/problem/<int:pk>/', api_views.delete_problem, name="delete_problem"),
    path('profile/stats/', api_views.ProfileStatsView.as_view(), name="profile_stats"),
    path("code/analysis/", api_views.AnalysisView.as_view(), name="analysis"),
    path('code/save_problem/', api_views.SaveProblemView.as_view(), name="save_problem"),
    path('courses/create_course/', api_views.create_course, name="create_course"),
    path('courses/enrol_course/<str:course_code>/', api_views.enrol_course, name="enrol_course"),
    path('courses/get_course/', api_views.get_course, name="get_course"),
    path('courses/delete/<str:del_type>/<int:del_id>/', api_views.delete_entity, name="delete_entity"),
    path('courses/get_global_problem_stats/<int:problem_id>/<int:course_id>/<str:role>/', api_views.get_global_problem_stats, name="get_global_problem_stats"),
    # path('save_problem/', code_views.SaveProblemView.as_view(), name="save_problem"),
]

web_app/app/urls.py
from django.contrib import admin
from django.urls import include, path
from users import views as user_views
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="index"),
    path('accounts/', include(('accounts.urls', 'accounts'), namespace="accounts")),
    path('code/', include(('code_analysis.urls', 'code_analysis'), namespace="code")),
    path('users/', include(('users.urls', 'users'), namespace="users")),
    path('about/', views.about, name="about"),
    path('api/', include(('api.urls', 'api'), namespace="api")),
    path('classes/', include(('classes.urls', 'classes'), namespace="classes")),
]

web_app/classes/urls.py
from django.urls import path
from . import views as course_views

urlpatterns = [
    # path('create_course_view/', course_views.create_course_view, name="create_course_view"),
    path('search_course_view/<str:user_role>/', course_views.search_course_view, name="search_course_view"),
    path('course_landing/<int:course_id>/', course_views.course_landing, name="course_landing"),
    path('delete_response/<str:del_type>/<int:course_id>/', course_views.delete_response, name="delete_response"),
    path('submission_overview/<int:course_id>/<int:prob_id>/', course_views.submission_overview, name="submission_overview"),
    path('problem_view/<int:problem_id>/<int:uid>/<str:role>/', course_views.problem_view, name="problem_view"),
]

web_app/users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views  as user_views

urlpatterns = [
    path('profile/<int:uid>/', user_views.profile, name="profile"),
    path('profile/delete_response/', user_views.delete_response, name="delete_response"),
    path('profile/solution/view/', user_views.solution_view, name="solution_view"),
    path('profile/problem/view/', user_views.problem_view, name="problem_view"),
]

web_app/templates/base.html
{% load static %}
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
{% bootstrap_messages %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@500;700;800&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Bungee+Shade&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    <link rel="icon" href="{% static 'images/icon.png' %}">
    <title>CGC - Code for Code's Sake</title>
</head>

<header>
    <!-- Fixed navbar -->
    <!-- Add fixed-top to navbar class if want to be fixed in place-->
    <nav class="navbar navbar-expand-md fixed-top navbar-dark">
        <a class="logo" href="{% url 'index' %}">CGC</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse"
            aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item bold">
                    <a class="nav-link" href="{% url 'index' %}">Home <span class="sr-only">(current)</span></a>
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:logout' %}">Logout</a>
                </li>
                <li class="nav-item"></li>
                    <a class="nav-link" href="{% url 'classes:search_course_view' user_role=user.profile.role %}">Courses</a>
                </li>
                <!-- <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:profile' uid=user.id %}">View Profile</a>
                </li> -->
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:register' %}">Register</a>
                </li>
                {% endif %}
                <li class="nav-item" style="float:right">
                    <div>
                        <a class="nav-link" href="{% url 'about' %}">About Us</a>
                    </div>
                </li>
            </ul>
        </div>
    </nav>
</header>

<body style="overscroll-behavior-x: none;margin-top:5%;">

    <!-- <div id="sidebar">
        {% block sidebar %}
        <ul>
            <li><a href="/">Home</a></li>
            <li><a href="/blog/">Blog</a></li>
        </ul>
        {% endblock %}
    </div> -->

    <div id="content">
        {% block content %}{% endblock %}
    </div>

    <footer>
        <!-- <div class="text-center">
            <a><img src="{% static 'images/github.png' %}"/></a>
        </div> -->
    </footer>

</body>

</html>

web_app/templates/code.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<div class="code-home">
    <div class="top_section">
        <img src="{% static 'images/back.png' %}" id="go_back" />
        <h1 class="problem_name text-left" style="text-transform:capitalize;margin-left:20px;"><br><u>{{ problem_name }}</u><br></h1>
    </div>
    <br>
    <p class="problem_desc" id="description" style="white-space:pre-wrap;margin-left:2em;">{{ problem_desc }}</p>
    <br>
    {% if sample_input %}
    <p>Sample input: {{ sample_input }}</p>
    <p>Sample output: {{ sample_output }} </p>
    {% endif %}

    <div class="row no-gutters">
        <div id="editor" class="col-sm-12 col-md-6 col-lg-6 col-xl-6 nopadding">
        </div>
        <div class="solution-info col-sm-12 col-md-6 col-lg-6 col-xl-6 nopadding">
            <form id="sub_form" action="" method="post" enc="multipart/form-data">

                {% csrf_token %}
                <div class="form-row">
                    <div class="form-group col-md-6 mb-0 col-lg-12">
                        {{ form.title }}
                    </div>
                </div>
                <br>
                <div class="form-row">
                    <div class="form-group col-md-6 mb-0 col-lg-12">
                        <input name="solution" id="solution_text" type="hidden">
                        <input type="hidden"> {{ form.user_id }} {{ form.problem_id }}
                    </div>
                    <input type="hidden" name="sub_type" value="solution">
                </div>


                <div id="problem_info">

                    <div id="result">
                        <p id="error_message" style="padding-top:10em;text-align:center;color:red;text-transform:italic;"></p>
                        <p id="overall_score" class="text-center"></p>
                        <div id="collapse_section">
                            <button type="button" class="collapsible"> Overview Stats </button>
                            <div id="collapse0" class="content" name="collapse_results">
                                <p id="overview_stats">
                                </p>

                            </div>
                            <button type="button" class="collapsible"> Sample Pseudocode </button>
                            <div id="collapse1" class="content" name="collapse_results">
                                <p id="pseudocode"></p>
                            </div>
                            <button id="lp_btn" type="button" class="collapsible"> Line Profiling </button>
                            <div id="collapse2" class="content" name="collapse_results">
                                <p id="line_profiling">
                                <p id="graph_space">
                                <div id='graph_heading'></div>
                                <div height='400px' width='400px' style='width:100%;height:100vh;position:relative;'>
                                    <canvas id='myChart' width='400' height='400'
                                        style='position:absolute;top:0;bottom:0;right:0;left:0;margin:auto;'></canvas>
                                </div>
                                </p>
                                </p>
                            </div>
                        </div>
                    </div>
                    <div class="text-center">
                        <button id="sub_btn" type="submit" class="text-center submit_btn">
                            <img src="{% static 'images/submit.png' %}" id="submit_img" alt="Unknown img" />
                            <p class="btn_text">Submit Your Code</p>
                        </button>
                    </div>
                    <div id="loader">
                        <div class="text-center">
                            <svg width="200" height="200" viewBox="0 0 100 100">
                                <polyline class="line-cornered stroke-still" points="0,0 100,0 100,100"
                                    stroke-width="10" fill="none"></polyline>
                                <polyline class="line-cornered stroke-still" points="0,0 0,100 100,100"
                                    stroke-width="10" fill="none"></polyline>
                                <polyline class="line-cornered stroke-animation" points="0,0 100,0 100,100"
                                    stroke-width="10" fill="none"></polyline>
                                <polyline class="line-cornered stroke-animation" points="0,0 0,100 100,100"
                                    stroke-width="10" fill="none"></polyline>
                            </svg>
                        </div>
                    </div>


                    <p style="visibility:hidden;" id="main_signature">{{ main_signature }}</p>


                </div>

            </form>




        </div>


    </div>


</div>

<div id="result"></div>

<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle"
    aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-lg" style="width:90%" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 style="color:black;text-align:center;" class="modal-title" id="modal_title">Detailed Breakdown</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div style="color:black" class="modal-body" id="modal_body">
            </div>
            <div style="color:black" class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/ace/1.4.12/ace.js" type="text/javascript" charset="utf-8"></script>
<script type="text/javascript" src="{% static 'js/editor.js' %}"></script>
<script type="text/javascript" src="{% static 'js/collapse.js' %}"></script>
<script type="text/javascript" src="{% static 'js/reset_results.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.min.js"></script>

{% endblock content %}

web_app/templates/index.html
{% extends "base.html" %} 
{% load static %}
{% block content %}
    
<div class="home">
    <div class="text-center showcase">
        <h1 class="cgc-title"> CGC </h1>
        <h1 class="second-title">Codē Gratia Codis</h1>
        <p>Or in plain english...code for code's sake!</p>
        <a href="#problems"><button class="scroll-down-btn" id="scroll-down-btn"> <img src="{% static 'images/scroll-down.png' %}"/></button></a>
    </div>

    <div class="container">
        <button type="button" class="collapsible">View Problems</button>
        <div class="content">
            <p class="problem_desc"></p>
            <a href="#">
                <div class="row">
                    <div class="col-lg-4">
                    <a href="{% url 'code:problem_view_general' category='mathematics' %}" class="field_desc">
                      <img class="rounded-circle" src="{% static 'images/math_pi.png' %}" alt="Generic placeholder image" width="140" height="140">
                      <br><br>
                      <h2>Mathematics</h2><br>
                      <p style="color:white;">Donec sed odio dui. Etiam porta sem malesuada magna mollis euismod. Nullam id dolor id nibh ultricies vehicula ut id elit. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Praesent commodo cursus magna.</p>
                    </a>
                    </div>
                    <div class="col-lg-4">
                    <a href="{% url 'code:problem_view_general' category='string_manipulation' %}" class="field_desc">
                      <img class="rounded-circle" src="{% static 'images/string_manipulation.png' %}"  alt="Generic placeholder image" width="140" height="140">
                      <br><br>
                      <h2>String Manipulation</h2><br>
                      <p style="color:white;">Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Cras mattis consectetur purus sit amet fermentum. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh.</p>
                    </a>
                    </div>
                    <div class="col-lg-4">
                    <a href="{% url 'code:problem_view_general' category='file_io' %}" class="field_desc">
                      <img class="rounded-circle" src="{% static 'images/file_io.png' %}"  alt="Generic placeholder image" width="140" height="140">
                      <br><br>
                      <h2>File I/O</h2><br>
                      <p style="color:white;">Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
                      </a>
                    </div>
                </div>
            </a>
            <p class="problem_author"></p>
        </div>
        <button type="button" class="collapsible">Brush up on your theory</button>
        <div class="content">
            <p class="problem_desc"></p>
            <a href="{% url 'code:problem_view_general' category='mathematics' %}">
                <div class="text-center">
                    <button type="button" class="text-center go_btn">
                        Enter
                    </button>
                </div>
            </a>
            <p class="problem_author"></p>
        </div>
        <button type="button" class="collapsible">Share your thoughts in our forum</button>
        <div class="content">
            <p class="problem_desc"></p>
            <a href="{% url 'code:problem_view_general' category='mathematics' %}">
                <div class="text-center">
                    <button type="button" class="text-center go_btn">
                        Enter
                    </button>
                </div>
            </a>
            <p class="problem_author"></p>
        </div>
    </div>


</div>


<script type="text/javascript" src="{% static 'js/collapse.js' %}"></script>
<script type="text/javascript" src="placeholder"></script>
<script type="text/javascript" src="placeholder"></script>
{% endblock %}

web_app/templates/prob_view_prof.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<div class="view_container row no-gutters">
    <h2 id="container_header" class="central_header" style="margin:25 0 0 20"></h2>

    <div id='lprof_btn_div' style="width:100%"></div>
    <div class="view_left col" style="text-align:left;" id="soln_left">
        <div id="overview_stats" class="individual_overview">
            <br>
            <h4><u>Your Problem:</u></h4><br><br>
            <div id="detailed_stats_div"></div>
            <br><h5><u>Source Code</u></h5><br>
            <div id="problem_code_div"></div><br><hr>
            <h5><u>Description</u></h5><br>
            <div id="problem_description_div"></div>
            
        </div>

    </div>


    <div class="view_right col" id="soln_right">
        <div id="detailed_stats">

            <br><div style="text-align:left;margin-left:25px;"><h4><u>Performance Scatter Plot</u></h4></div><br>
            <div height='400px' width='400px' style='margin-top:10%;width:80%;height:60vh;position:relative;'>
                <canvas id='myChart' width='400' height='200'
                    style='position:absolute;top:0;bottom:0;right:0;left:0;margin:auto;'></canvas>
            </div>

        </div>

    </div>


</div>
<div style="text-align:center;margin-top:35px;">
    <a href="" data-toggle='modal' data-target='#modalDeleteConfirm'><button type='button'
            class='text-center go_btn btn-sm' style='width:15%;padding:10px;background-color:rgb(240, 79, 79)'
            id='delete_button'>Delete</button></a>
</div>
<div style="text-align:center;margin-top:35px;" id="delete_response"></div>

<div class="modal fade" id="modalDeleteConfirm" tabindex="-1" role="dialog"
    aria-labelledby="modalDeleteConfirmCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-sm" style="width:90%" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 style="color:black;text-align:center;" class="modal-title" id="modal_title">Confirm Deletion</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div style="color:black" class="modal-body" id="modal_body">
                Are you sure you want to delete your problem? - All associated solution data will be deleted also.
            </div>
            <div style="color:black" class="modal-footer" id="confirm_delete">
                <button type="button" class="btn btn-secondary" style="background-color: rgb(240, 79, 79);"
                    data-dismiss="modal" id="confirm">Confirm</button>
                <button type="button" class="btn btn-secondary" data-dismiss="modal" id="cancel">Cancel</button>
            </div>
        </div>
    </div>
</div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.min.js"></script>
{{ problem.analysis|json_script:"problem_analysis" }}
{{ problem.metadata.description|json_script:"problem_description" }}
{{ problem.name|json_script:"problem_name" }}
<script>
    const prob_id = "{{ prob_id }}"
    const csrf_token = "{{ csrf_token }}"
</script>
<script type="text/javascript" src="{% static 'js/prob_view_prof.js' %}"></script>
{% endblock %}

web_app/templates/problem_upload.html
{% extends "base.html" %} 
{% load static %} 
{% load crispy_forms_tags %}

{% block content %}
    
    <div class="row no-gutters">
        <div class="col-sm-12 col-md-12 col-lg-12 col-xl-12 nopadding">
            <div>
                <h2 class="text-center" style="padding:20px;"><u>Upload Your Problem Below</u></h2>
            </div>
            <div class="text-left upload_form" style="padding-left:20px;">
                <form id="prob_form" action="" method="post" enc="multipart/form-data">
                    {% csrf_token %}
                    <div>
                        <div class="form-group col-sm-12 col-md-12 col-lg-12 col-xl-12">{{ form.author_id }}</div>
                        <div class="form-group col-sm-12 col-md-12 col-lg-12 col-xl-12 item"><span class="upload-form-field">Problem Name:</span> <span class="problem_name">{{ form.name }}</span></div>
                        <div class="form-group col-sm-12 col-md-12 col-lg-12 col-xl-12 item"><span class="upload-form-field">Problem Description:</span><span class="problem_desc">&nbsp&nbsp{{ form.description }}</span></div>

                        <div class="form-group col-sm-12 col-md-12 col-lg-12 col-xl-12 item"><span class="upload-form-field">Metadata File (.yaml format):</span>{{ form.meta_file }}</div>
                        <div class="form-group col-sm-12 col-md-12 col-lg-12 col-xl-12 item"><span class="upload-form-field">Problem Script:</span>{{ form.program }}</div>
                        {% if cat == 'file_io' %}
                           <div class="form-group col-sm-12 col-md-12 col-lg-12 col-xl-12 item"><span class="upload-form-field">Target File(s):</span>{{ form.target_file }}</div>
                        {% elif cat == 'default' %}
                        <div class="form-group col-sm-12 col-md-12 col-lg-12 col-xl-12 item">
                            <span class="upload-form-field">Inputs (.json format):</span>{{ form.inputs }}
                        </div>
                        {% endif %}
                        <div class="form-group col-sm-12 col-md-12 col-lg-12 col-xl-12 item"><span class="upload-form-field">Optional Data File (.json format):</span>{{ form.data_file }}</div>
                        {{ form.category }}
                    </div>
                    <div class="text-center">
                        <button id="sub_btn" type="submit" class="submit_form_btn">UPLOAD</button>
                    </div>
                </form><br>
            <div><p id="form_upload_res" style="text-align:center;"></p></div>
            </div>
        </div>
    </div>


    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script type="text/javascript" src="{% static 'js/problem_upload.js' %}"></script> 
{% endblock %}

web_app/templates/problem_view.html
{% extends "base.html" %} 
{% load static %}
{% block content %}
    
<div class="home">

    <div class="container" id="problems">
        <br>
        <h1 style="text-align:center;text-transform:capitalize;"><u>{{ category }}</u></h1>
        <br>
        {% for problem in problems %}
        <button type="button" class="collapsible">{{ problem.name }} ({{ problem.metadata.difficulty }}) </button>
        <div class="content">
            <p class="problem_desc" style="white-space: pre-wrap;">{{ problem.metadata.description }}</p>
            <a href="{% url 'code:solution' prob_id=problem.id %}">
                <div class="text-center">
                    <button type="button" class="text-center go_btn">
                        Get started
                    </button>
                </div>
            </a>
            <p class="problem_author"> Created by {{ problem.author__user__username }}</p>
        </div>

        {% endfor %} 
    </div>



</div>


<script type="text/javascript" src="{% static 'js/collapse.js' %}"></script>
<script type="text/javascript" src="placeholder"></script>
<script type="text/javascript" src="placeholder"></script>
{% endblock %}

web_app/templates/problem_view_general.html
{% extends "base.html" %} 
{% load static %}
{% block content %}
    
<div class="home">

    <div class="container" id="problems">
        <br>
        <h1 style="text-align:center;text-transform:capitalize;"><u>{{ category }}</u></h1>
        <br>
        {% for problem in problems %}
        <button type="button" class="collapsible">{{ problem.name }} ({{ problem.metadata.difficulty }}) </button>
        <div class="content">
            <p class="problem_desc" style="white-space: pre-wrap;">{{ problem.metadata.description }}</p>
            <a href="{% url 'code:solution' prob_id=problem.id %}">
                <div class="text-center">
                    <button type="button" class="text-center go_btn">
                        Get started
                    </button>
                </div>
            </a>
            <p class="problem_author"> Created by {{ problem.author__user__username }}</p>
        </div>

        {% endfor %} 
    </div>



</div>


<script type="text/javascript" src="{% static 'js/collapse.js' %}"></script>
<script type="text/javascript" src="placeholder"></script>
<script type="text/javascript" src="placeholder"></script>
{% endblock %}

web_app/templates/profile.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<div class="view_container">
    <div class="view_left" style="border:none">
        <img class="rounded-circle" style="background-color:white;" src="{% static 'images/generic_user.png' %}"
            alt="Generic user image" width="140" height="140">
        <br><br>
        {% if profile.user__is_active %}
        <h2 style="color:#06D6A0;">{{ profile.user__username }}</h2><br>
        {% else %}
        <h2 style="color:silver">{{ profile.user__username }}</h2><br>
        {% endif %}
        <p style="color:white;">Contact me: {{ profile.user__email }}</p>
        <p style="color:white;">Level: {{ profile.level }}</p>
        <p style="color:white;">About me: {{ profile.about }}</p>
        <br><br><br>
        <div>
            <button id="toggle" value=0 class="btn text-center btn-dark">View Your Uploaded Problems</button>
        </div>
    </div>

    <div class="view_right" id="prof_right" style="border:none">
        <div id="stats_view">

        </div>

    </div>


</div>

<script type="text/javascript" src="{% static 'js/collapse.js' %}"></script>
<script type="text/javascript" src="{% static 'js/profile.js' %}"></script>

{% endblock %}

web_app/templates/soln_view.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<div class="view_container row no-gutters">


   <h2 id="container_header" class="central_header" style="margin:25 0 0 20"></h2><br>

   <div id='lprof_btn_div' style="width:100%"></div>
   <div class="view_left col" style="text-align:left;" id="soln_left">
      <div id="overview_stats" class="individual_overview">
         <br>
         <h4><u>Your Solution</u></h4><br>

      </div>

   </div>


   <div class="view_right col" id="soln_right">
      <div id="detailed_stats">


         <div height='400px' width='400px' style='margin-top:10%;width:80%;height:60vh;position:relative;'>
            <canvas id='myChart' width='400' height='200'
               style='position:absolute;top:0;bottom:0;right:0;left:0;margin:auto;'></canvas>
         </div>

      </div>

   </div>


</div>
<div style="text-align:center;margin-top:35px;">
   <a href="{% url 'code:solution' prob_id=prob_id %}"><button type='button' class='text-center go_btn btn-sm'
         style='width:15%;padding:10px;background-color:#1d2b5b'>Try Again</button></a>
   <a href="" data-toggle='modal' data-target='#exampleModalCenter'><button type='button' class='text-center go_btn btn-sm' 
         style='width:15%;padding:10px;background-color:rgb(240, 79, 79)' id='delete_button'>Delete</button></a>
</div>
<div style="text-align:center;margin-top:35px;" id="delete_response"></div>

<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-sm" style="width:90%" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 style="color:black;text-align:center;" class="modal-title" id="modal_title">Confirm Deletion</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div style="color:black" class="modal-body" id="modal_body">
               Are you sure you want to delete your solution?
            </div>
            <div style="color:black" class="modal-footer" id="confirm_delete">
               <button type="button" class="btn btn-secondary" style="background-color: rgb(240, 79, 79);" data-dismiss="modal" id="confirm">Confirm</button>
                <button type="button" class="btn btn-secondary" data-dismiss="modal" id="cancel">Cancel</button>
            </div>
        </div>
    </div>
</div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.min.js"></script>
<script>
   const soln_id = "{{ soln_id }}"
   const prob_id = "{{ prob_id }}"
   const csrf_token = "{{ csrf_token }}"
</script>
<script type="text/javascript" src="{% static 'js/soln_view.js' %}"></script>
{% endblock %}