web_app/api/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views as api_views

urlpatterns = [
    path('profile/delete/solution/<int:pk>/', api_views.delete_solution, name="delete_solution"),
    path('profile/delete/problem/<int:pk>/', api_views.delete_problem, name="delete_problem"),
    path('profile/stats/', api_views.ProfileStatsView.as_view(), name="profile_stats"),
    path("code/analysis/", api_views.AnalysisView.as_view(), name="analysis"),
    path('code/save_problem/', api_views.SaveProblemView.as_view(), name="save_problem"),
    path('courses/create_course/', api_views.create_course, name="create_course"),
    path('courses/enrol_course/<str:course_code>/', api_views.enrol_course, name="enrol_course"),
    path('courses/get_course/', api_views.get_course, name="get_course"),
    path('courses/delete/<str:del_type>/<int:del_id>/', api_views.delete_entity, name="delete_entity"),
    path('courses/get_global_problem_stats/<int:problem_id>/<int:course_id>/<str:role>/', api_views.get_global_problem_stats, name="get_global_problem_stats"),
    # path('save_problem/', code_views.SaveProblemView.as_view(), name="save_problem"),
]

web_app/app/urls.py
from django.contrib import admin
from django.urls import include, path
from users import views as user_views
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="index"),
    path('accounts/', include(('accounts.urls', 'accounts'), namespace="accounts")),
    path('code/', include(('code_analysis.urls', 'code_analysis'), namespace="code")),
    path('users/', include(('users.urls', 'users'), namespace="users")),
    path('about/', views.about, name="about"),
    path('api/', include(('api.urls', 'api'), namespace="api")),
    path('classes/', include(('classes.urls', 'classes'), namespace="classes")),
]

web_app/classes/urls.py
from django.urls import path
from . import views as course_views

urlpatterns = [
    # path('create_course_view/', course_views.create_course_view, name="create_course_view"),
    path('search_course_view/<str:user_role>/', course_views.search_course_view, name="search_course_view"),
    path('course_landing/<int:course_id>/', course_views.course_landing, name="course_landing"),
    path('delete_response/<str:del_type>/<int:course_id>/', course_views.delete_response, name="delete_response"),
    path('submission_overview/<int:course_id>/<int:prob_id>/', course_views.submission_overview, name="submission_overview"),
    path('problem_view/<int:problem_id>/<int:uid>/<str:role>/', course_views.problem_view, name="problem_view"),
]

web_app/code_analysis/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views as code_views

urlpatterns = [
    path('solution/<int:prob_id>', code_views.solution_upload, name="solution"),
    path('problem_upload/<str:problem_cat>/<int:course_id>', code_views.problem_upload, name="problem_upload"),
    path("problem_view/<str:category>", code_views.problem_view, name="problem_view"),
]

web_app/users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views  as user_views

urlpatterns = [
    path('profile/<int:uid>/', user_views.profile, name="profile"),
    path('profile/delete_response/', user_views.delete_response, name="delete_response"),
    path('profile/solution/view/', user_views.solution_view, name="solution_view"),
    path('profile/problem/view/', user_views.problem_view, name="problem_view"),
]

web_app/templates/courses/course_landing.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div class="home">
    <div class="container" id="problems">
    <br>
    <h1>{{ course.name }}</h1>
    <div>
        <p>{{ course.description }}</p> 
    </div>
    <h3 style="text-align:center;text-transform:capitalize;"><u>Problems</u></h1>
    {% if problems %}
        {% for problem in problems %}
            <button type="button" class="collapsible">{{ problem.name }} ({{ problem.metadata.difficulty }}) </button>
            <div class="content">
                <p class="problem_desc" style="white-space: pre-wrap;">{{ problem.metadata.description }}</p>
                {% if user.profile.role == "student" %}
                <a href="{% url 'code:solution' prob_id=problem.id %}">
                    <div class="text-center">
                        <button type="button" class="text-center go_btn">
                            Give it a shot
                        </button>
                        
                    </div>
                </a>
                <br>
                <a href="{% url 'classes:problem_view' problem_id=problem.id uid=user.id role=user.profile.role %}">
                    <div class="text-center">
                        <button type="button" class="text-center go_btn" style="background-color:#1d2b5b;">
                            Check out your stats
                        </button>
                        
                    </div>
                </a>
                <p class="problem_author"> Created by {{ problem.author__username }}</p>
                {% elif user.profile.role == "tutor" %}
                <a href="{% url 'classes:submission_overview' course_id=course.id prob_id=problem.id %}">
                    <div class="text-center">
                        <button type="button" class="text-center go_btn">
                            Check out the status of your problem
                        </button>
                    </div>
                </a>
            {% endif %}
            </div>
        {% endfor %}
    {% else %}
        <p>There do not appear to be any problems associated with this course</p>
    {% endif %}
    <br><br>
    {% if user.profile.role == "tutor" %}
    <a class="nav-link dropdown-toggle text-center go_btn" href="#" data-toggle="dropdown">Upload A New Problem</a>
    <ul class="dropdown-menu">
        <li><a class="dropdown-item" href="{% url 'code:problem_upload' problem_cat='default' course_id=course.id %}">Default</a></li>
        <li><a class="dropdown-item" href="{% url 'code:problem_upload' problem_cat='file_io' course_id=course.id %}">File I/O</a></li>
    </ul>
    {% endif %}
    {% if user.id == course.tutor_id %}
    <div style="text-align:center;margin-top:35px;">
        <a href="" data-toggle='modal' data-target='#modalDeleteConfirm'><button name="del_btn" type='button'
                class='text-center go_btn btn-sm' style='width:15%;padding:10px;background-color:rgb(240, 79, 79)'
                id="deactivate_course">Deactivate Course</button></a>
    </div>
    <div style="text-align:center;margin-top:35px;" id="deactivation_response"></div>
    
    <div class="modal fade" id="modalDeleteConfirm" tabindex="-1" role="dialog"
        aria-labelledby="modalDeleteConfirmCenterTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered modal-sm" style="width:90%" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 style="color:black;text-align:center;" class="modal-title" id="modal_title">Confirm Deactivation</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div style="color:black" class="modal-body" id="modal_body">
                    Are you sure you want to deactivate this course?
                </div>
                <div style="color:black" class="modal-footer" id="confirm_deactivate">
                    <button type="button" class="btn btn-secondary" style="background-color: rgb(240, 79, 79);"
                        data-dismiss="modal" id="confirm">Confirm</button>
                    <button type="button" class="btn btn-secondary" data-dismiss="modal" id="cancel">Cancel</button>
                </div>
            </div>
        </div>
    </div>
    {% endif %}

</div>
</div>

<script type="text/javascript">window.course_id = "{{ course.id }}"; window.csrf_token = "{{ csrf_token }}";</script>
<script type="text/javascript" src="{% static 'js/utils/collapse.js' %}"></script>
<script type="text/javascript" src="{% static 'js/courses/course_landing.js' %}"></script>
{% endblock content %}

web_app/templates/courses/course_view.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div class="home">
<div class="container" id="problems">

{% if user.profile.role == "student" %}
    <br>
    <h1 style="text-align:center;text-transform:capitalize;"><u>Courses</u></h1>
    <br>
    {% if courses %}
        {% for course in courses %}
        <button type="button" class="collapsible">{{ course.name }}</button>
        <div class="content">
            <p class="problem_desc" style="white-space: pre-wrap;">{{ course.description }}</p>
            <a href="{% url 'classes:course_landing' course_id=course.id %}">
                <div class="text-center">
                    <button type="button" class="text-center go_btn">
                        Go to Course
                    </button>
                </div>
            </a>
            <p class="problem_author"> Tutor: {{ course.tutor }}</p>
        </div>

        {% endfor %}
    {% else %}
        <p style="text-align:center;">
            You are not enrolled in any courses!<br><br>
            Why not use the following credentials to enrol in our sample course and test out the app?
            <div class="text-center">
            <ul style="list-style-type:none;">
                <li>
                    Course Code: MIT_CS201
                </li>
                <li>
                    Course Password: test_teacher123
                </li>
            </ul>
            <button class="scroll-down-btn" id="scroll-down-btn"> <img src="{% static 'images/scroll-down.png' %}"/></button>
        </div>
        </p>
    {% endif %}

    <br><br>
    <div style="text-align:center">
    <button id="enrol_form_btn" value="0" type='button' class='text-center go_btn btn-sm'
    style='width:15%;padding:10px;background-color:#1d2b5b'>Click here to enrol in a new course</button>
    </div>
    <br>
    <div id="enrol_form_div" class="row no-gutters">
        <div class="col-sm-12 col-md-12 col-lg-12 col-xl-12 nopadding">
            <div class="text-center">
            <div style="padding-left:20px;" class="form-group col-sm-12 col-md-12 col-lg-12 col-xl-12 item"><span class="upload-form-field">Course Code (Max Length: 15)</span> <span name="course_code" class="problem_name">{{ form.code }}</span></div>
            
                <button id="search_button" type="button" class="text-center go_btn">
                    Search
                </button>
            </div><br>
        </div>
    </div>
    <p id="course_fetch_error" style="text-align:center;margin:5 0 5 0;color:red;"></p>
    <div id="course_info"></div>
    <div id="effective_enrol" class="text-left upload_form" style="padding-left:20px;visibility:hidden;">
        <form id="enrol_course_form" action="" method="post" enc="multipart/form-data">
            {% csrf_token %}
            <div class="form-group col-sm-12 col-md-12 col-lg-12 col-xl-12 item"><span id="passcode_span" class="upload-form-field"></span> <span id="passcode_entry_field" class="problem_name">{{ form.password }}</span></div>
            <div class="text-center">
                <button id="sub_btn" type="submit" class="submit_form_btn">ENROL</button>
            </div>
        </form>
    </div>
    
    <div class="text-center"><p id="ce_res"></p></div>


{% elif user.profile.role == "tutor" %}

<br>
<h1 style="text-align:center;text-transform:capitalize;"><u>Your Courses</u></h1>
<br>
{% if courses %}
{% for course in courses %}
<button type="button" class="collapsible">{{ course.name }}</button>
<div class="content">
    <p class="problem_desc" style="white-space: pre-wrap;">{{ course.description }}</p>
    <a href="{% url 'classes:course_landing' course_id=course.id %}">
        <div class="text-center">
            <button type="button" class="text-center go_btn">
                Go to Course
            </button>
        </div>
    </a>
</div>
{% endfor %}
{% else %}
<p style="white-space: pre-wrap;">Oops, you have not created any courses yet!</p>
{% endif %}
<br><br>
<div style="text-align:center">
<button id="cc_form_btn" value="0">Click here to create a new course</button>
</div>
<br>
<div id="cc_form_div" style="visibility:hidden" class="row no-gutters">
    <div class="col-sm-12 col-md-12 col-lg-12 col-xl-12 nopadding">
        <div>
            <h2 class="text-center" style="padding:20px;"><u>Create Your Course Below</u></h2>
        </div>
        <div class="text-left upload_form" style="padding-left:20px;">
            <form id="create_course_form" action="" method="post" enc="multipart/form-data">
                {% csrf_token %}
                <div class="form-group col-sm-12 col-md-12 col-lg-12 col-xl-12 item"><span class="upload-form-field">Course Name:</span> <span class="problem_name">{{ form.name }}</span></div>
                <div class="form-group col-sm-12 col-md-12 col-lg-12 col-xl-12 item"><span class="upload-form-field">Course Code:</span> <span class="problem_name">{{ form.code }}</span></div>
                <div class="form-group col-sm-12 col-md-12 col-lg-12 col-xl-12 item"><span class="upload-form-field">Course Password:</span> <span id="password_main" class="problem_name">{{ form.password }}</span></div>
                <div class="form-group col-sm-12 col-md-12 col-lg-12 col-xl-12 item"><span class="upload-form-field">Confirm Password:</span> <span id="password2" class="problem_name">{{ form.confirm_password }}</span></div>
                <div class="text-center">
                    <p id="password_unmatch" style="color:red;padding: 5 0 5 0;"></p>
                </div>
                <div class="form-group col-sm-12 col-md-12 col-lg-12 col-xl-12 item"><span class="upload-form-field">Course Description:</span> <span class="problem_desc">{{ form.description }}</span></div>
                <div class="text-center">
                    <button id="sub_btn" type="submit" class="submit_form_btn">CREATE</button>
                </div>
            </form>
        </div>
        <div><p id="cc_res" style="text-align:center;"></p></div>
    </div>
</div>
{% endif %}
</div>
</div>
<script type="text/javascript">window.CSRF_TOKEN = "{{ csrf_token }}";</script> 
<script type="text/javascript" src="{% static 'js/utils/collapse.js' %}"></script>
<script type="text/javascript" src="{% static 'js/courses/course.js' %}"></script> 
{% endblock content %}

web_app/templates/courses/delete_response.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<div style="text-align:center;margin-top:20%">
    <h5 style="color:#06D6A0;">{{ de_msg }}</h5><br>
    {% if del_type == "problem" %}
        <a class="nav-link dropdown-toggle text-center go_btn" href="#" data-toggle="dropdown">Upload A New Problem</a>
        <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{% url 'code:problem_upload' problem_cat='default' course_id=course.id %}">Default</a></li>
            <li><a class="dropdown-item" href="{% url 'code:problem_upload' problem_cat='file_io' course_id=course.id %}">File I/O</a></li>
        </ul>
    <br>
    {% endif %}
    <a href="{% url 'classes:course_landing' course_id=course.id %}"><button type='button' class='text-center go_btn btn-sm'
        style='width:15%;padding:10px;background-color:#1d2b5b'>Return to course page</button></a>
    <br><br>

</div>

{% endblock %}

web_app/templates/courses/problem_view.html
{% extends "base.html" %}
{% load static %}
{% block content %}
{% if solution %}
<div style="margin: 7% 0 0 5%">
    {% if user.profile.role == "tutor" %}
    <h2><u>{{ solution.submitter.username|title }}'s submission for {{ solution.problem.name }} </u></h2>
    {% elif user.profile.role == "student" %}
    <h2><u>Your submission for {{ solution.problem.name }}</u></h2>
    {% endif %}
    <h4>{{ solution.course.name }} : {{ solution.course.code }}</h4> 
    <h5>({{ solution.date_submitted }})</h5><br><br> 

    <div style="float:right;margin:0 10% 0 0;">
      <a id="output_review" class="nav-link dropdown-toggle text-left" href="#" data-toggle="dropdown">Review Outputs</a>
      <ul id="output_review_dd" class="dropdown-menu">
          
          <li><a class="dropdown-item" data-toggle="modal" data-target="#exampleModalCenter">Test 2</a></li>
      </ul>
    </div>

    <p id="score"></p>
    <p id="cprof"></p>
    <p id="memprof"></p><br>
    <div style="display:flex;margin:2% 1% 0% 1%;">
    <p style="float:left;width:45%;overflow-x:scroll;" id="solution_text"></p>
    <p style="width:10%;"></p>
    <p style="float:right;width:45%;overflow-x:scroll;" id="pseudocode"></p>
    </div>
</div>


<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle"
    aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-lg" style="width:90%" role="document">
        <div class="modal-content" style="background-color: #101010;">
            <div class="modal-header" style="background-color: rgb(220, 215, 215);">
                <h5 style="color:black;text-align:center;" class="modal-title" id="modal_title"></h5>
                <span id="output_btn_space" style="margin-left:20px;"><button id="output_type_btn" style="float:right;margin:0 0 0 10;"></button></span>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div style="color:black" class="modal-body" id="modal_body">
              <table id="modal_table" class="table-striped table-black" style="width:100%;background-color:#101010;"></table>
            </div>
            <div style="color:black" class="modal-footer" id="modal_footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

<br><br>
{% if other_solutions %}
<div style="display:block;margin: 2% 0 0 5%">
<h4><u>Previous Solutions:</u></h4><br>
<table class="table table-striped table-light">
    <thead>
      <tr>
        <th scope="col">Date Submitted</th>
        <th scope="col">Score</th>
      </tr>
    </thead>
    <tbody>
{% for alt_soln in other_solutions %}
<tr>
      <td><a class="nav-link" href="{% url 'classes:problem_view' problem_id=alt_soln.problem.id uid=alt_soln.submitter.id role=user.profile.id %}?which=other&soln_id={{ alt_soln.id }}">{{ alt_soln.date_submitted }}</a></td>
      {% if alt_soln.analysis.passed %}
      <td><span style="color:#06D6A0">{{ alt_soln.analysis.score }}%</span></td>
      {% else %}
      <td><span style="color:rgb(240, 79, 79)">{{ alt_soln.analysis.score }}%</span></td>  
      {% endif %}
</tr>
{% endfor %}
</tbody>
</table>
</div><br><br>
{% endif %}
<button type='button' class='text-center go_btn btn-sm' id='stat_btn'
    style='width:15%;padding:10px;background-color:#1d2b5b'>View Score Chart</button>
<div height='400px' width='400px' style='margin-top:10%;width:80%;height:60vh;position:relative;'>
    <canvas id='myChart' width='400' height='200'
        style='position:absolute;top:0;bottom:0;right:0;left:0;margin:auto;'></canvas>
    </div>
<br><br>
{% else %}
<div style="text-align:center;margin-top:20%">
    <h5 style="color:#06D6A0;">Oops, it looks like you haven't any recorded submissions for this problem!</h5>
    <br>
    <a href="{% url 'code:solution' prob_id=problem_id %}"><button type='button' class='text-center go_btn btn-sm'
            style='width:15%;padding:10px;background-color:#1d2b5b'>Try it out</button></a>
</div>
{% endif %}

{{ solution.analysis|json_script:"soln_analysis" }}
<script>
  const solution_analysis = JSON.parse(document.getElementById('soln_analysis').textContent);
  const submitter_name = "{{ solution.submitter.username }}";
  const date_sub = "{{ solution.date_submitted }}";
  const role = "{{ user.profile.role }}";
  const course_id = "{{ solution.course.id }}";
  const problem_id = "{{ solution.problem.id }}";
</script>

{% if solution.course.tutor_id == user.id %}
<script>const valid_tutor = true;</script>
{% else %}
<script>const valid_tutor = false;</script>
{% endif %}
{% if solution.submitter.id == user.id %}
<script>const valid_student = true;</script>
{% else %}
<script>const valid_student = false;</script>
{% endif %}
{% if latest %}
<script>const latest = true;</script>
{% else %}
<script>const latest = false;</script>
{% endif %}


<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.min.js"></script>
<script type="text/javascript">const csrf_token = "{{ csrf_token }}";</script>
<script type="text/javascript" src="{% static 'js/courses/problem_view.js' %}"></script>
<script type="text/javascript" src="{% static 'js/charts/problem_view_charts.js' %}"></script>

{% endblock content %}

web_app/templates/courses/submission_overview.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<br><br>
<div style="text-align:center;">
    <h1 style="color:#06D6A0;"><u>Submission Overview: {{ problem.name }}</u></h1>
</div>
<hr>
{% if solutions %}
<br><br>
<h2 style="color:rgba(255, 255, 255, 0.845);">&nbsp&nbspSubmitted:</h2>
<br><br>
<table class="table table-striped table-light">
    <thead>
      <tr>
        <th scope="col">UserName</th>
        <th scope="col">Score</th>
        <th scope="col">Date Submitted</th>
        <th scope="col">See More</th>
      </tr>
    </thead>
    <tbody>
{% for solution in solutions %}
<tr>
  {% if solution.analysis.passed %}
    <td><a style="color:#06D6A0" class="nav-link" href="{% url 'users:profile' uid=solution.submitter.id %}">{{ solution.submitter.username }}</a></td>
    <td><span style="color:#06D6A0">{{ solution.analysis.score }}%</span></td>
    {% else %}
    <td><a style="color:rgb(240, 79, 79)" class="nav-link" href="{% url 'users:profile' uid=solution.submitter.id %}">{{ solution.submitter.username }}</a></td>
    <td><span style="color:rgb(240, 79, 79)">{{ solution.analysis.score }}%</span></td>  
    {% endif %}
    <td>{{ solution.date_submitted }}</td>
    <td><a href="{% url 'classes:problem_view' problem_id=solution.problem.id uid=solution.submitter.id role=user.profile.role %}">Submission Breakdown</a></td>
  </tr>
{% endfor %}
    </tbody>
</table>
{% endif %}
<br><br>
{% if other_students %}
<h2 style="color:rgba(181, 180, 180, 0.502);">&nbsp&nbspNot Submitted:</h2><br><br>
<table class="table table-striped table-dark" >
    <thead>
      <tr>
        <th scope="col">UserName</th>
      </tr>
    </thead>
    <tbody>
{% for other_student in other_students %}
<tr>
    <td><a class="nav-link" href="{% url 'users:profile' uid=other_student.id %}">{{ other_student.username }}</a></td>
</tr>
{% endfor %}
</table>
{% endif %}
<br><br>
<div>
<button type='button' class='text-center go_btn btn-sm' id='stat_btn'
    style='width:15%;padding:10px;background-color:#1d2b5b'>View Score Chart</button>
<div height='400px' width='400px' style='margin-top:10%;width:80%;height:60vh;position:relative;'>
    <canvas id='myChart' width='400' height='200'
        style='position:absolute;top:0;bottom:0;right:0;left:0;margin:auto;'></canvas>
    </div>
  </div>
<br><br>

<script>
  const role = "{{ user.profile.role }}"
  const submitter_name = null
  const course_id = "{{ problem.course_id }}";
  const problem_id = "{{ problem.id }}";
  const pass_threshold = "{{ problem.metadata.pass_threshold }}"
</script>

{% if problem.author_id == user.id %}
<script>const valid_tutor = true;</script>
{% else %}
<script>const valid_tutor = false;</script>
{% endif %}

<script type="text/javascript">window.course_id = "{{ course.id }}"; window.csrf_token = "{{ csrf_token }}";</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.min.js"></script>
<script type="text/javascript" src="{% static 'js/charts/problem_view_charts.js' %}"></script>
<script type="text/javascript" src="{% static 'js/courses/submission_overview.js' %}"></script>

{% endblock content %}