web_app/api/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views as api_views

urlpatterns = [
    path('profile/delete/solution/<int:pk>/', api_views.delete_solution, name="delete_solution"),
    path('profile/delete/problem/<int:pk>/', api_views.delete_problem, name="delete_problem"),
    path('profile/stats/', api_views.ProfileStatsView.as_view(), name="profile_stats"),
    path("code/analysis/", api_views.AnalysisView.as_view(), name="analysis"),
    path('code/save_problem/', api_views.SaveProblemView.as_view(), name="save_problem"),
    path('courses/create_course/', api_views.create_course, name="create_course"),
    path('courses/enrol_course/<str:course_code>/', api_views.enrol_course, name="enrol_course"),
    path('courses/get_course/', api_views.get_course, name="get_course"),
    path('courses/delete/<str:del_type>/<int:del_id>/', api_views.delete_entity, name="delete_entity"),
    path('courses/get_global_problem_stats/<int:problem_id>/<int:course_id>/<str:role>/', api_views.get_global_problem_stats, name="get_global_problem_stats"),
    # path('save_problem/', code_views.SaveProblemView.as_view(), name="save_problem"),
]

web_app/app/urls.py
from django.contrib import admin
from django.urls import include, path
from users import views as user_views
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="index"),
    path('accounts/', include(('accounts.urls', 'accounts'), namespace="accounts")),
    path('code/', include(('code_analysis.urls', 'code_analysis'), namespace="code")),
    path('users/', include(('users.urls', 'users'), namespace="users")),
    path('about/', views.about, name="about"),
    path('api/', include(('api.urls', 'api'), namespace="api")),
    path('classes/', include(('classes.urls', 'classes'), namespace="classes")),
]

web_app/classes/urls.py
from django.urls import path
from . import views as course_views

urlpatterns = [
    # path('create_course_view/', course_views.create_course_view, name="create_course_view"),
    path('search_course_view/<str:user_role>/', course_views.search_course_view, name="search_course_view"),
    path('course_landing/<int:course_id>/', course_views.course_landing, name="course_landing"),
    path('delete_response/<str:del_type>/<int:course_id>/', course_views.delete_response, name="delete_response"),
    path('submission_overview/<int:course_id>/<int:prob_id>/', course_views.submission_overview, name="submission_overview"),
    path('problem_view/<int:problem_id>/<int:uid>/<str:role>/', course_views.problem_view, name="problem_view"),
]

web_app/users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views  as user_views

urlpatterns = [
    path('profile/<int:uid>/', user_views.profile, name="profile"),
    path('profile/delete_response/', user_views.delete_response, name="delete_response"),
    path('profile/solution/view/', user_views.solution_view, name="solution_view"),
    path('profile/problem/view/', user_views.problem_view, name="problem_view"),
]

web_app/templates/main/about.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<div class="icons_link">Icons sourced from: <a href="https://icons8.com">Icons8.com</a></div>
{% endblock content %}

web_app/templates/main/code.html
{% extends "base.html" %}
{% load static %}
{% block content %}

{% if attempt_number <= allowed_attempts %}
<div class="code-home">
    <div class="top_section">
        <img src="{% static 'images/back.png' %}" id="go_back" />
        <h1 class="problem_name text-left" style="text-transform:capitalize;margin-left:20px;"><br><u>{{ problem.name }}</u><br></h1>
        <h4 class="problem_desc text-left" id="attempt_hdr"></h4>
    </div>
    <br>
    <p class="problem_desc" id="description" style="white-space:pre-wrap;margin-left:2em;">{{ problem_desc }}</p>
    <br>
    {% if problem.metadata.sample_answer %}
    <div style="text-align:left">
        <button type='button' id="sample_answer" class='text-center go_btn btn-sm'
            style='width:15%;padding:10px;background-color:#1d2b5b'>Show Sample Answer</button>
    </div>
    <br>
    {% endif %}
    {% if sample_input %}
    <p>Sample input: {{ sample_input }}</p>
    <p>Sample output: {{ sample_output }} </p>
    {% endif %}

    <div class="row no-gutters">
        <div id="editor" class="col-sm-12 col-md-6 col-lg-6 col-xl-6 nopadding">
        </div>
        <div class="solution-info col-sm-12 col-md-6 col-lg-6 col-xl-6 nopadding">
            <form id="sub_form" action="" method="post" enc="multipart/form-data">

                {% csrf_token %}
                <div class="form-row">
                    <div class="form-group col-md-6 mb-0 col-lg-12">
                        {{ form.title }}
                    </div>
                </div>
                <br>
                <div class="form-row">
                    <div class="form-group col-md-6 mb-0 col-lg-12">
                        <input name="solution" id="solution_text" type="hidden">
                        <input type="hidden"> {{ form.user_id }} {{ form.problem_id }} {{ form.course_id }}
                    </div>
                    <input type="hidden" name="sub_type" value="solution">
                </div>


                <div id="problem_info">

                    <div id="result">
                        <p id="error_message" style="padding-top:10em;text-align:center;color:red;text-transform:italic;"></p>
                        <p id="overall_score" class="text-center"></p>
                        <div id="collapse_section">
                            <button type="button" class="collapsible"> Overview Stats </button>
                            <div id="collapse0" class="content" name="collapse_results">
                                <p id="overview_stats">
                                </p>

                            </div>
                            <button type="button" class="collapsible"> Sample Pseudocode </button>
                            <div id="collapse1" class="content" name="collapse_results">
                                <p id="pseudocode"></p>
                            </div>
                            <button id="lp_btn" type="button" class="collapsible"> Line Profiling </button>
                            <div id="collapse2" class="content" name="collapse_results">
                                <p id="line_profiling">
                                <p id="graph_space">
                                <div id='graph_heading'></div>
                                <div height='400px' width='400px' style='width:100%;height:100vh;position:relative;'>
                                    <canvas id='myChart' width='400' height='400'
                                        style='position:absolute;top:0;bottom:0;right:0;left:0;margin:auto;'></canvas>
                                </div>
                                </p>
                                </p>
                            </div>
                        </div>
                    </div>
                    <div class="text-center">
                        <button id="sub_btn" type="submit" class="text-center submit_btn">
                            <img src="{% static 'images/submit.png' %}" id="submit_img" alt="Unknown img" />
                            <p class="btn_text">Submit Your Code</p>
                        </button>
                    </div>
                    <div id="loader">
                        <div class="text-center">
                            <svg width="200" height="200" viewBox="0 0 100 100">
                                <polyline class="line-cornered stroke-still" points="0,0 100,0 100,100"
                                    stroke-width="10" fill="none"></polyline>
                                <polyline class="line-cornered stroke-still" points="0,0 0,100 100,100"
                                    stroke-width="10" fill="none"></polyline>
                                <polyline class="line-cornered stroke-animation" points="0,0 100,0 100,100"
                                    stroke-width="10" fill="none"></polyline>
                                <polyline class="line-cornered stroke-animation" points="0,0 0,100 100,100"
                                    stroke-width="10" fill="none"></polyline>
                            </svg>
                        </div>
                    </div>


                    <p style="visibility:hidden;" id="main_signature">{{ main_signature }}</p>


                </div>

            </form>




        </div>


    </div>


</div>

<div id="result"></div>

<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle"
    aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-lg" style="width:90%" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 style="color:black;text-align:center;" class="modal-title" id="modal_title">Detailed Breakdown</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div style="color:black; overflow-x: scroll; overflow-y:scroll;" class="modal-body" id="modal_body">
                <div style="color:black; overflow-x: scroll; overflow-y:scroll;" class="modal-body" id="modal_body_inner"></div>
                <h5 id="mtsuc_hdr" style="color:#06D6A0;"></h5><br>
                <table id="mtsuc" class="table-striped table-black" style="width:100%;background-color:#101010;border-width: 5px;border-color: #06D6A0;"></table>
                <br>
                <h5 id="mterr_hdr" style="color:rgb(240, 79, 79)"></h5><br>
                <table id="mterr" class="table-striped table-black" style="width:100%;background-color:#101010;border-width: 5px;border-color: rgb(240, 79, 79);"></table>
            </div>
            <div style="color:black" class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>
{% else %}
<div style="text-align:center;margin-top:20%">
    <h5 style="color:#06D6A0;">Oops, you appear to have exceeded the maximum number of attempts for this problem</h5><br>
    <a href="{% url 'classes:problem_view' problem_id=problem.id uid=user.id role=user.profile.role %}">
        <div class="text-center">
            <button type="button" class="text-center go_btn" style="background-color:#1d2b5b;">
                Check out your stats
            </button>
        </div>
    </a>
</div>
{% endif %}
{{ problem.metadata|json_script:"problem_metadata" }}
<script>
const metadata = JSON.parse(document.getElementById('problem_metadata').textContent);
</script>
<script>const attempt_number = "{{ attempt_number }}";</script>
<script>const allowed_attempts = "{{ allowed_attempts }}";</script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/ace/1.4.12/ace.js" type="text/javascript" charset="utf-8"></script>
<script type="text/javascript" src="{% static 'js/main/code.js' %}"></script>
<script type="text/javascript" src="{% static 'js/utils/collapse.js' %}"></script>
<script type="text/javascript" src="{% static 'js/utils/reset_results.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.min.js"></script>

{% endblock content %}

web_app/templates/main/course_view.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div class="home">
<div class="container" id="problems">

{% if user.profile.role == "student" %}
    <br>
    <h1 style="text-align:center;text-transform:capitalize;"><u>Courses</u></h1>
    <br>
    {% if courses %}
        {% for course in courses %}
        <button type="button" class="collapsible">{{ course.name }}</button>
        <div class="content">
            <p class="problem_desc" style="white-space: pre-wrap;">{{ course.description }}</p>
            <a href="{% url 'classes:course_landing' course_id=course.id %}">
                <div class="text-center">
                    <button type="button" class="text-center go_btn">
                        Go to Course
                    </button>
                </div>
            </a>
            <p class="problem_author"> Tutor: {{ course.tutor }}</p>
        </div>

        {% endfor %}
    {% else %}
        <p style="text-align:center;">You are not enrolled in any courses!</p>
    {% endif %}
    <br><br>
    <div style="text-align:center">
    <button id="enrol_form_btn" value="0">Click here to enrol in a new course</button>
    </div>
    <br>
    <div id="enrol_form_div" class="row no-gutters" style="visibility:hidden;">
        <div class="col-sm-12 col-md-12 col-lg-12 col-xl-12 nopadding">
            <div>
                <h2 class="text-center" style="padding:20px;"><u>Enrol in a Course Now!</u></h2>
            </div>
            <div class="text-left upload_form" style="padding-left:20px;">
                <form id="enrol_course_form" action="" method="post" enc="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-group col-sm-12 col-md-12 col-lg-12 col-xl-12 item"><span class="upload-form-field">Course Code (Max Length => 15):</span> <span class="problem_name">{{ form.code }}</span></div>
                    <div class="text-center">
                        <button id="sub_btn" type="submit" class="submit_form_btn">ENROL</button>
                    </div>
                </form>
            </div>
            <div><p id="ce_res" style="text-align:center;"></p></div>
        </div>
    </div>

{% elif user.profile.role == "tutor" %}

<br>
<h1 style="text-align:center;text-transform:capitalize;"><u>Your Courses</u></h1>
<br>
{% if courses %}
{% for course in courses %}
<button type="button" class="collapsible">{{ course.name }}</button>
<div class="content">
    <p class="problem_desc" style="white-space: pre-wrap;">{{ course.description }}</p>
    <a href="{% url 'classes:course_landing' course_id=course.id %}">
        <div class="text-center">
            <button type="button" class="text-center go_btn">
                Go to Course
            </button>
        </div>
    </a>
</div>
{% endfor %}
{% else %}
<p style="white-space: pre-wrap;">Oops, you have not created any courses yet!</p>
{% endif %}
<br><br>
<div style="text-align:center">
<button id="cc_form_btn" value="0">Click here to create a new course</button>
</div>
<br>
<div id="cc_form_div" style="visibility:hidden" class="row no-gutters">
    <div class="col-sm-12 col-md-12 col-lg-12 col-xl-12 nopadding">
        <div>
            <h2 class="text-center" style="padding:20px;"><u>Create Your Course Below</u></h2>
        </div>
        <div class="text-left upload_form" style="padding-left:20px;">
            <form id="create_course_form" action="" method="post" enc="multipart/form-data">
                {% csrf_token %}
                <div class="form-group col-sm-12 col-md-12 col-lg-12 col-xl-12 item"><span class="upload-form-field">Course Name:</span> <span class="problem_name">{{ form.name }}</span></div>
                <div class="form-group col-sm-12 col-md-12 col-lg-12 col-xl-12 item"><span class="upload-form-field">Course Code:</span> <span class="problem_name">{{ form.code }}</span></div>
                <div class="form-group col-sm-12 col-md-12 col-lg-12 col-xl-12 item"><span class="upload-form-field">Course Description:</span> <span class="problem_desc">{{ form.description }}</span></div>
                <div class="text-center">
                    <button id="sub_btn" type="submit" class="submit_form_btn">CREATE</button>
                </div>
            </form>
        </div>
        <div><p id="cc_res" style="text-align:center;"></p></div>
    </div>
</div>
{% endif %}
</div>
</div>
<script type="text/javascript">window.CSRF_TOKEN = "{{ csrf_token }}";</script> 
<script type="text/javascript" src="{% static 'js/utils/collapse.js' %}"></script>
<script type="text/javascript" src="{% static 'js/main/course.js' %}"></script> 
{% endblock content %}

web_app/templates/main/index.html
{% extends "base.html" %} 
{% load static %}
{% block content %}
    
<div class="home">
    <div class="text-center showcase">
        <h1 class="cgc-title"> CGC </h1>
        <h1 class="second-title">Codē Gratia Codis</h1>
        <br><br>
        {% if user.is_authenticated %}
        <p>Welcome {{ user.username }} ...!</p>
        {% else %}
        <p>It looks like you are not yet logged in. Why not test out the app by following these simple steps:<br>
            <div style="text-align:left;">
            <ol>
                <li>Register an account</li>
                <li>Go to your 'Courses' and enrol in the course 'MIT_CS201' with password 'test_teacher123'</li>
                <li>Try to solve any of the problems proposed in this sample course</li>
            </ol>
            </div>
        </p>
        {% endif %}
        <a href="#problems"><button class="scroll-down-btn" id="scroll-down-btn"> <img src="{% static 'images/scroll-down.png' %}"/></button></a>
    </div>

    <div class="container">
        {% if user.is_authenticated %}
        <button type="button" class="collapsible">Courses</button>
        
        <div class="content">
            
            <a href="{% url 'classes:search_course_view' user_role=user.profile.role %}">
                <div class="text-center">
                    <br>
                    <button type="button" class="text-center go_btn">
                        Check out your courses here =>
                    </button>
                </div>
            </a>
            <p class="problem_author"></p>
        </div>
        {% endif %}
        <!-- <button type="button" class="collapsible">View Problems</button>
        <div class="content">
            <p class="problem_desc"></p>
            <a href="#">
                <div class="row">
                    <div class="col-lg-4">
                    <a href="{% url 'code:problem_view' category='mathematics' %}" class="field_desc">
                      <img class="rounded-circle" src="{% static 'images/math_pi.png' %}" alt="Generic placeholder image" width="140" height="140">
                      <br><br>
                      <h2>Mathematics</h2><br>
                      <p style="color:white;">Donec sed odio dui. Etiam porta sem malesuada magna mollis euismod. Nullam id dolor id nibh ultricies vehicula ut id elit. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Praesent commodo cursus magna.</p>
                    </a>
                    </div>
                    <div class="col-lg-4">
                    <a href="{% url 'code:problem_view' category='string_manipulation' %}" class="field_desc">
                      <img class="rounded-circle" src="{% static 'images/string_manipulation.png' %}"  alt="Generic placeholder image" width="140" height="140">
                      <br><br>
                      <h2>String Manipulation</h2><br>
                      <p style="color:white;">Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Cras mattis consectetur purus sit amet fermentum. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh.</p>
                    </a>
                    </div>
                    <div class="col-lg-4">
                    <a href="{% url 'code:problem_view' category='file_io' %}" class="field_desc">
                      <img class="rounded-circle" src="{% static 'images/file_io.png' %}"  alt="Generic placeholder image" width="140" height="140">
                      <br><br>
                      <h2>File I/O</h2><br>
                      <p style="color:white;">Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
                      </a>
                    </div>
                    <div class="col-lg-4">
                        <a href="{% url 'code:problem_view' category='networking' %}" class="field_desc">
                          <img class="rounded-circle" src="{% static 'images/network.png' %}"  alt="Generic placeholder image" width="140" height="140">
                          <br><br>
                          <h2>Networking</h2><br>
                          <p style="color:white;">Duis mollis, est non commodo luctus, nisi erat jknporttitor ligula, eget lacinia odio sem nec elit. Cras mattis consectetur purus sit amet fermentum. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh.</p>
                        </a>
                        </div>
                </div>
            </a>
            <p class="problem_author"></p>
        </div> -->
        <button type="button" class="collapsible">Brush up on your theory</button>
        <div class="content">
            <p class="problem_desc"></p>
            <a href="#">
                <div class="text-center">
                    <button type="button" class="text-center go_btn">
                        Enter
                    </button>
                </div>
            </a>
            <p class="problem_author"></p>
        </div>
        <button type="button" class="collapsible">Share your thoughts in our forum</button>
        <div class="content">
            <p class="problem_desc"></p>
            <a href="#">
                <div class="text-center">
                    <button type="button" class="text-center go_btn">
                        Enter
                    </button>
                </div>
            </a>
            <p class="problem_author"></p>
        </div>
    </div>


</div>


<script type="text/javascript" src="{% static 'js/utils/collapse.js' %}"></script>
{% endblock %}

web_app/templates/main/problem_upload.html
{% extends "base.html" %} 
{% load static %} 
{% load crispy_forms_tags %}

{% block content %}
    
    <div class="row no-gutters">
        <div class="col-sm-12 col-md-12 col-lg-12 col-xl-12 nopadding">
            <div>
                <h2 class="text-center" style="padding:20px;"><u>Upload Your Problem Below</u></h2>
            </div>
            <div class="text-left upload_form" style="padding-left:20px;"></div>
                <form id="prob_form" action="" method="post" enc="multipart/form-data">
                    {% csrf_token %}
                    <div>
                        <div class="form-group col-sm-12 col-md-12 col-lg-12 col-xl-12">{{ form.author_id }}</div>
                        <div class="form-group col-sm-12 col-md-12 col-lg-12 col-xl-12">{{ form.course_id }}</div>
                        <div class="form-group col-sm-12 col-md-12 col-lg-12 col-xl-12 item"><span class="upload-form-field">Problem Name:</span> <span class="problem_name">{{ form.name }}</span></div>
                        <div class="form-group col-sm-12 col-md-12 col-lg-12 col-xl-12 item"><span class="upload-form-field">Problem Description:</span><span class="problem_desc">&nbsp&nbsp{{ form.description }}</span></div>

                        <div class="form-group col-sm-12 col-md-12 col-lg-12 col-xl-12 item"><span class="upload-form-field">Metadata File (.yaml format):</span>{{ form.meta_file }}</div>
                        <div class="form-group col-sm-12 col-md-12 col-lg-12 col-xl-12 item"><span class="upload-form-field">Problem Script:</span>{{ form.program }}</div>
                        {% if cat == 'file_io' %}
                           <div class="form-group col-sm-12 col-md-12 col-lg-12 col-xl-12 item"><span class="upload-form-field">Target File(s):</span>{{ form.target_file }}</div>
                        {% elif cat == 'default' %}
                        <div class="form-group col-sm-12 col-md-12 col-lg-12 col-xl-12 item">
                            <span class="upload-form-field">Inputs (.json format):</span>{{ form.inputs }}
                        </div>

                        {% endif %}
                        <div class="form-group col-sm-12 col-md-12 col-lg-12 col-xl-12 item"><span class="upload-form-field">Optional Data File (.json format):</span>{{ form.data_file }}</div>
                        <div class="form-group col-sm-12 col-md-12 col-lg-12 col-xl-12 item">
                            <span class="upload-form-field">Optional Sample Answer: </span>{{ form.sample_answer }}
                        </div>
                        {{ form.category }}
                    </div>
                    <div class="text-center">
                        <button id="sub_btn" type="submit" class="submit_form_btn">UPLOAD</button>
                    </div>
                </form><br>
            <div><p id="form_upload_res" style="text-align:center;"></p></div>
            </div>
        </div>
    </div>

    <script type="text/javascript"> window.CSRF_TOKEN = "{{ csrf_token }}"; </script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script type="text/javascript" src="{% static 'js/main/problem_upload.js' %}"></script> 
{% endblock %}

web_app/templates/main/problem_view.html
{% extends "base.html" %} 
{% load static %}
{% block content %}
    
<div class="home">

    <div class="container" id="problems">
        <br>
        <h1 style="text-align:center;text-transform:capitalize;"><u>{{ category }}</u></h1>
        <br>
        {% for problem in problems %}
        <button type="button" class="collapsible">{{ problem.name }} ({{ problem.metadata.difficulty }}) </button>
        <div class="content">
            <p class="problem_desc" style="white-space: pre-wrap;">{{ problem.metadata.description }}</p>
            <a href="{% url 'code:solution' prob_id=problem.id %}">
                <div class="text-center">
                    <button type="button" class="text-center go_btn">
                        Get started
                    </button>
                </div>
            </a>
            <p class="problem_author"> Created by {{ problem.author__user__username }}</p>
        </div>

        {% endfor %} 
    </div>



</div>


<script type="text/javascript" src="{% static 'js/utils/collapse.js' %}"></script>

{% endblock %}